// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: db.proto

#include "db.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class tb_user_infoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<tb_user_info>
      _instance;
} _tb_user_info_default_instance_;
class tb_user_info_fileDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<tb_user_info_file>
      _instance;
} _tb_user_info_file_default_instance_;
namespace protobuf_db_2eproto {
void InitDefaultstb_user_infoImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_tb_user_info_default_instance_;
    new (ptr) ::tb_user_info();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tb_user_info::InitAsDefaultInstance();
}

void InitDefaultstb_user_info() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultstb_user_infoImpl);
}

void InitDefaultstb_user_info_fileImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_db_2eproto::InitDefaultstb_user_info();
  {
    void* ptr = &::_tb_user_info_file_default_instance_;
    new (ptr) ::tb_user_info_file();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tb_user_info_file::InitAsDefaultInstance();
}

void InitDefaultstb_user_info_file() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultstb_user_info_fileImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, userid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, userex_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, accout_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, password_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, accoutname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, email_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, phonenum_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, usertype_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, registertime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, registeraddr_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, opendevicelock_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, onlone_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, lastloginouttime_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info, selfinvitekey_),
  9,
  10,
  0,
  1,
  2,
  3,
  4,
  11,
  5,
  6,
  12,
  13,
  7,
  8,
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info_file, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info_file, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tb_user_info_file, uinfo_),
  ~0u,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 19, sizeof(::tb_user_info)},
  { 33, 39, sizeof(::tb_user_info_file)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_tb_user_info_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::_tb_user_info_file_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "db.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\010db.proto\"\234\002\n\014tb_user_info\022\016\n\006userId\030\001 "
      "\001(\r\022\016\n\006userEx\030\002 \001(\r\022\016\n\006accout\030\003 \001(\t\022\020\n\010p"
      "assword\030\004 \001(\t\022\022\n\naccoutName\030\005 \001(\t\022\r\n\005ema"
      "il\030\006 \001(\t\022\020\n\010phoneNum\030\007 \001(\t\022\020\n\010userType\030\010"
      " \001(\r\022\024\n\014registerTime\030\t \001(\t\022\024\n\014registerAd"
      "dr\030\n \001(\t\022\026\n\016openDeviceLock\030\013 \001(\010\022\016\n\006onLo"
      "ne\030\014 \001(\010\022\030\n\020lastLoginOutTime\030\r \001(\t\022\025\n\rse"
      "lfInviteKey\030\016 \001(\t\"1\n\021tb_user_info_file\022\034"
      "\n\005uinfo\030\001 \003(\0132\r.tb_user_info"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 348);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "db.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_db_2eproto

// ===================================================================

void tb_user_info::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int tb_user_info::kUserIdFieldNumber;
const int tb_user_info::kUserExFieldNumber;
const int tb_user_info::kAccoutFieldNumber;
const int tb_user_info::kPasswordFieldNumber;
const int tb_user_info::kAccoutNameFieldNumber;
const int tb_user_info::kEmailFieldNumber;
const int tb_user_info::kPhoneNumFieldNumber;
const int tb_user_info::kUserTypeFieldNumber;
const int tb_user_info::kRegisterTimeFieldNumber;
const int tb_user_info::kRegisterAddrFieldNumber;
const int tb_user_info::kOpenDeviceLockFieldNumber;
const int tb_user_info::kOnLoneFieldNumber;
const int tb_user_info::kLastLoginOutTimeFieldNumber;
const int tb_user_info::kSelfInviteKeyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

tb_user_info::tb_user_info()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_db_2eproto::InitDefaultstb_user_info();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tb_user_info)
}
tb_user_info::tb_user_info(const tb_user_info& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  accout_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_accout()) {
    accout_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accout_);
  }
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_password()) {
    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  accoutname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_accoutname()) {
    accoutname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accoutname_);
  }
  email_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_email()) {
    email_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.email_);
  }
  phonenum_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_phonenum()) {
    phonenum_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.phonenum_);
  }
  registertime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_registertime()) {
    registertime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.registertime_);
  }
  registeraddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_registeraddr()) {
    registeraddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.registeraddr_);
  }
  lastloginouttime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_lastloginouttime()) {
    lastloginouttime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lastloginouttime_);
  }
  selfinvitekey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_selfinvitekey()) {
    selfinvitekey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.selfinvitekey_);
  }
  ::memcpy(&userid_, &from.userid_,
    static_cast<size_t>(reinterpret_cast<char*>(&onlone_) -
    reinterpret_cast<char*>(&userid_)) + sizeof(onlone_));
  // @@protoc_insertion_point(copy_constructor:tb_user_info)
}

void tb_user_info::SharedCtor() {
  _cached_size_ = 0;
  accout_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  accoutname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  email_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  phonenum_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  registertime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  registeraddr_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lastloginouttime_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  selfinvitekey_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&userid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&onlone_) -
      reinterpret_cast<char*>(&userid_)) + sizeof(onlone_));
}

tb_user_info::~tb_user_info() {
  // @@protoc_insertion_point(destructor:tb_user_info)
  SharedDtor();
}

void tb_user_info::SharedDtor() {
  accout_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  accoutname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  email_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  phonenum_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  registertime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  registeraddr_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  lastloginouttime_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  selfinvitekey_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void tb_user_info::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tb_user_info::descriptor() {
  ::protobuf_db_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_db_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const tb_user_info& tb_user_info::default_instance() {
  ::protobuf_db_2eproto::InitDefaultstb_user_info();
  return *internal_default_instance();
}

tb_user_info* tb_user_info::New(::google::protobuf::Arena* arena) const {
  tb_user_info* n = new tb_user_info;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void tb_user_info::Clear() {
// @@protoc_insertion_point(message_clear_start:tb_user_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      GOOGLE_DCHECK(!accout_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*accout_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000002u) {
      GOOGLE_DCHECK(!password_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*password_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000004u) {
      GOOGLE_DCHECK(!accoutname_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*accoutname_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000008u) {
      GOOGLE_DCHECK(!email_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*email_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000010u) {
      GOOGLE_DCHECK(!phonenum_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*phonenum_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000020u) {
      GOOGLE_DCHECK(!registertime_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*registertime_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000040u) {
      GOOGLE_DCHECK(!registeraddr_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*registeraddr_.UnsafeRawStringPointer())->clear();
    }
    if (cached_has_bits & 0x00000080u) {
      GOOGLE_DCHECK(!lastloginouttime_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
      (*lastloginouttime_.UnsafeRawStringPointer())->clear();
    }
  }
  if (cached_has_bits & 0x00000100u) {
    GOOGLE_DCHECK(!selfinvitekey_.IsDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited()));
    (*selfinvitekey_.UnsafeRawStringPointer())->clear();
  }
  if (cached_has_bits & 15872u) {
    ::memset(&userid_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&onlone_) -
        reinterpret_cast<char*>(&userid_)) + sizeof(onlone_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool tb_user_info::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tb_user_info)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional uint32 userId = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {
          set_has_userid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &userid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 userEx = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          set_has_userex();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &userex_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string accout = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_accout()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->accout().data(), static_cast<int>(this->accout().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tb_user_info.accout");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string password = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->password().data(), static_cast<int>(this->password().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tb_user_info.password");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string accoutName = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_accoutname()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->accoutname().data(), static_cast<int>(this->accoutname().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tb_user_info.accoutName");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string email = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_email()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->email().data(), static_cast<int>(this->email().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tb_user_info.email");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string phoneNum = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_phonenum()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->phonenum().data(), static_cast<int>(this->phonenum().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tb_user_info.phoneNum");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional uint32 userType = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {
          set_has_usertype();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &usertype_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string registerTime = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(74u /* 74 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_registertime()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->registertime().data(), static_cast<int>(this->registertime().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tb_user_info.registerTime");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string registerAddr = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(82u /* 82 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_registeraddr()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->registeraddr().data(), static_cast<int>(this->registeraddr().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tb_user_info.registerAddr");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool openDeviceLock = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u /* 88 & 0xFF */)) {
          set_has_opendevicelock();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &opendevicelock_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional bool onLone = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(96u /* 96 & 0xFF */)) {
          set_has_onlone();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &onlone_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string lastLoginOutTime = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(106u /* 106 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_lastloginouttime()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->lastloginouttime().data(), static_cast<int>(this->lastloginouttime().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tb_user_info.lastLoginOutTime");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string selfInviteKey = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(114u /* 114 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_selfinvitekey()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->selfinvitekey().data(), static_cast<int>(this->selfinvitekey().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "tb_user_info.selfInviteKey");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tb_user_info)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tb_user_info)
  return false;
#undef DO_
}

void tb_user_info::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tb_user_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 userId = 1;
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->userid(), output);
  }

  // optional uint32 userEx = 2;
  if (cached_has_bits & 0x00000400u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->userex(), output);
  }

  // optional string accout = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->accout().data(), static_cast<int>(this->accout().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.accout");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->accout(), output);
  }

  // optional string password = 4;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->password(), output);
  }

  // optional string accoutName = 5;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->accoutname().data(), static_cast<int>(this->accoutname().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.accoutName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->accoutname(), output);
  }

  // optional string email = 6;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->email().data(), static_cast<int>(this->email().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.email");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->email(), output);
  }

  // optional string phoneNum = 7;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->phonenum().data(), static_cast<int>(this->phonenum().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.phoneNum");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->phonenum(), output);
  }

  // optional uint32 userType = 8;
  if (cached_has_bits & 0x00000800u) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(8, this->usertype(), output);
  }

  // optional string registerTime = 9;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->registertime().data(), static_cast<int>(this->registertime().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.registerTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->registertime(), output);
  }

  // optional string registerAddr = 10;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->registeraddr().data(), static_cast<int>(this->registeraddr().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.registerAddr");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      10, this->registeraddr(), output);
  }

  // optional bool openDeviceLock = 11;
  if (cached_has_bits & 0x00001000u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(11, this->opendevicelock(), output);
  }

  // optional bool onLone = 12;
  if (cached_has_bits & 0x00002000u) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(12, this->onlone(), output);
  }

  // optional string lastLoginOutTime = 13;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lastloginouttime().data(), static_cast<int>(this->lastloginouttime().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.lastLoginOutTime");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      13, this->lastloginouttime(), output);
  }

  // optional string selfInviteKey = 14;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selfinvitekey().data(), static_cast<int>(this->selfinvitekey().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.selfInviteKey");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      14, this->selfinvitekey(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tb_user_info)
}

::google::protobuf::uint8* tb_user_info::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tb_user_info)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional uint32 userId = 1;
  if (cached_has_bits & 0x00000200u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->userid(), target);
  }

  // optional uint32 userEx = 2;
  if (cached_has_bits & 0x00000400u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->userex(), target);
  }

  // optional string accout = 3;
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->accout().data(), static_cast<int>(this->accout().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.accout");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->accout(), target);
  }

  // optional string password = 4;
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->password().data(), static_cast<int>(this->password().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->password(), target);
  }

  // optional string accoutName = 5;
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->accoutname().data(), static_cast<int>(this->accoutname().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.accoutName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->accoutname(), target);
  }

  // optional string email = 6;
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->email().data(), static_cast<int>(this->email().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.email");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->email(), target);
  }

  // optional string phoneNum = 7;
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->phonenum().data(), static_cast<int>(this->phonenum().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.phoneNum");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->phonenum(), target);
  }

  // optional uint32 userType = 8;
  if (cached_has_bits & 0x00000800u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(8, this->usertype(), target);
  }

  // optional string registerTime = 9;
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->registertime().data(), static_cast<int>(this->registertime().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.registerTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->registertime(), target);
  }

  // optional string registerAddr = 10;
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->registeraddr().data(), static_cast<int>(this->registeraddr().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.registerAddr");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        10, this->registeraddr(), target);
  }

  // optional bool openDeviceLock = 11;
  if (cached_has_bits & 0x00001000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(11, this->opendevicelock(), target);
  }

  // optional bool onLone = 12;
  if (cached_has_bits & 0x00002000u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(12, this->onlone(), target);
  }

  // optional string lastLoginOutTime = 13;
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->lastloginouttime().data(), static_cast<int>(this->lastloginouttime().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.lastLoginOutTime");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        13, this->lastloginouttime(), target);
  }

  // optional string selfInviteKey = 14;
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->selfinvitekey().data(), static_cast<int>(this->selfinvitekey().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "tb_user_info.selfInviteKey");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        14, this->selfinvitekey(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tb_user_info)
  return target;
}

size_t tb_user_info::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tb_user_info)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 255u) {
    // optional string accout = 3;
    if (has_accout()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->accout());
    }

    // optional string password = 4;
    if (has_password()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->password());
    }

    // optional string accoutName = 5;
    if (has_accoutname()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->accoutname());
    }

    // optional string email = 6;
    if (has_email()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->email());
    }

    // optional string phoneNum = 7;
    if (has_phonenum()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->phonenum());
    }

    // optional string registerTime = 9;
    if (has_registertime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->registertime());
    }

    // optional string registerAddr = 10;
    if (has_registeraddr()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->registeraddr());
    }

    // optional string lastLoginOutTime = 13;
    if (has_lastloginouttime()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->lastloginouttime());
    }

  }
  if (_has_bits_[8 / 32] & 16128u) {
    // optional string selfInviteKey = 14;
    if (has_selfinvitekey()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->selfinvitekey());
    }

    // optional uint32 userId = 1;
    if (has_userid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->userid());
    }

    // optional uint32 userEx = 2;
    if (has_userex()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->userex());
    }

    // optional uint32 userType = 8;
    if (has_usertype()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::UInt32Size(
          this->usertype());
    }

    // optional bool openDeviceLock = 11;
    if (has_opendevicelock()) {
      total_size += 1 + 1;
    }

    // optional bool onLone = 12;
    if (has_onlone()) {
      total_size += 1 + 1;
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tb_user_info::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tb_user_info)
  GOOGLE_DCHECK_NE(&from, this);
  const tb_user_info* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const tb_user_info>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tb_user_info)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tb_user_info)
    MergeFrom(*source);
  }
}

void tb_user_info::MergeFrom(const tb_user_info& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tb_user_info)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_accout();
      accout_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accout_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_password();
      password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_accoutname();
      accoutname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.accoutname_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_email();
      email_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.email_);
    }
    if (cached_has_bits & 0x00000010u) {
      set_has_phonenum();
      phonenum_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.phonenum_);
    }
    if (cached_has_bits & 0x00000020u) {
      set_has_registertime();
      registertime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.registertime_);
    }
    if (cached_has_bits & 0x00000040u) {
      set_has_registeraddr();
      registeraddr_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.registeraddr_);
    }
    if (cached_has_bits & 0x00000080u) {
      set_has_lastloginouttime();
      lastloginouttime_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.lastloginouttime_);
    }
  }
  if (cached_has_bits & 16128u) {
    if (cached_has_bits & 0x00000100u) {
      set_has_selfinvitekey();
      selfinvitekey_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.selfinvitekey_);
    }
    if (cached_has_bits & 0x00000200u) {
      userid_ = from.userid_;
    }
    if (cached_has_bits & 0x00000400u) {
      userex_ = from.userex_;
    }
    if (cached_has_bits & 0x00000800u) {
      usertype_ = from.usertype_;
    }
    if (cached_has_bits & 0x00001000u) {
      opendevicelock_ = from.opendevicelock_;
    }
    if (cached_has_bits & 0x00002000u) {
      onlone_ = from.onlone_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void tb_user_info::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tb_user_info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tb_user_info::CopyFrom(const tb_user_info& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tb_user_info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tb_user_info::IsInitialized() const {
  return true;
}

void tb_user_info::Swap(tb_user_info* other) {
  if (other == this) return;
  InternalSwap(other);
}
void tb_user_info::InternalSwap(tb_user_info* other) {
  using std::swap;
  accout_.Swap(&other->accout_);
  password_.Swap(&other->password_);
  accoutname_.Swap(&other->accoutname_);
  email_.Swap(&other->email_);
  phonenum_.Swap(&other->phonenum_);
  registertime_.Swap(&other->registertime_);
  registeraddr_.Swap(&other->registeraddr_);
  lastloginouttime_.Swap(&other->lastloginouttime_);
  selfinvitekey_.Swap(&other->selfinvitekey_);
  swap(userid_, other->userid_);
  swap(userex_, other->userex_);
  swap(usertype_, other->usertype_);
  swap(opendevicelock_, other->opendevicelock_);
  swap(onlone_, other->onlone_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata tb_user_info::GetMetadata() const {
  protobuf_db_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_db_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void tb_user_info_file::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int tb_user_info_file::kUinfoFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

tb_user_info_file::tb_user_info_file()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_db_2eproto::InitDefaultstb_user_info_file();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tb_user_info_file)
}
tb_user_info_file::tb_user_info_file(const tb_user_info_file& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_),
      _cached_size_(0),
      uinfo_(from.uinfo_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:tb_user_info_file)
}

void tb_user_info_file::SharedCtor() {
  _cached_size_ = 0;
}

tb_user_info_file::~tb_user_info_file() {
  // @@protoc_insertion_point(destructor:tb_user_info_file)
  SharedDtor();
}

void tb_user_info_file::SharedDtor() {
}

void tb_user_info_file::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* tb_user_info_file::descriptor() {
  ::protobuf_db_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_db_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const tb_user_info_file& tb_user_info_file::default_instance() {
  ::protobuf_db_2eproto::InitDefaultstb_user_info_file();
  return *internal_default_instance();
}

tb_user_info_file* tb_user_info_file::New(::google::protobuf::Arena* arena) const {
  tb_user_info_file* n = new tb_user_info_file;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void tb_user_info_file::Clear() {
// @@protoc_insertion_point(message_clear_start:tb_user_info_file)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  uinfo_.Clear();
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool tb_user_info_file::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tb_user_info_file)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tb_user_info uinfo = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_uinfo()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tb_user_info_file)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tb_user_info_file)
  return false;
#undef DO_
}

void tb_user_info_file::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tb_user_info_file)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .tb_user_info uinfo = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->uinfo_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->uinfo(static_cast<int>(i)), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:tb_user_info_file)
}

::google::protobuf::uint8* tb_user_info_file::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tb_user_info_file)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .tb_user_info uinfo = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->uinfo_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->uinfo(static_cast<int>(i)), deterministic, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tb_user_info_file)
  return target;
}

size_t tb_user_info_file::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tb_user_info_file)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  // repeated .tb_user_info uinfo = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->uinfo_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->uinfo(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void tb_user_info_file::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tb_user_info_file)
  GOOGLE_DCHECK_NE(&from, this);
  const tb_user_info_file* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const tb_user_info_file>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tb_user_info_file)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tb_user_info_file)
    MergeFrom(*source);
  }
}

void tb_user_info_file::MergeFrom(const tb_user_info_file& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tb_user_info_file)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  uinfo_.MergeFrom(from.uinfo_);
}

void tb_user_info_file::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tb_user_info_file)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void tb_user_info_file::CopyFrom(const tb_user_info_file& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tb_user_info_file)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool tb_user_info_file::IsInitialized() const {
  return true;
}

void tb_user_info_file::Swap(tb_user_info_file* other) {
  if (other == this) return;
  InternalSwap(other);
}
void tb_user_info_file::InternalSwap(tb_user_info_file* other) {
  using std::swap;
  uinfo_.InternalSwap(&other->uinfo_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata tb_user_info_file::GetMetadata() const {
  protobuf_db_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_db_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
